[package]
name = "ruckus"
version = "0.1.0"
# build = "build.rs"
authors = ["Drew Prentice <scalarwaves@null.net>"]
edition = "2018"

[lib]
name = "ruckus"
path = "src/lib.rs"

[dependencies]
libc = "0.2.43"

[build-dependencies]
bindgen = "0.43.1"
cc = "1.0.25"

# [workspace]
# members = [
#     "ruckus-cli"
# ]