[package]
name = "ruckus"
version = "0.1.0"
authors = ["Andrew Prentice <scalarwaves@null.net>"]
edition = "2018"

[lib]
name = "ruckus"
path = "src/lib.rs"

[dependencies]
chuck_sys = { path = "../chuck_sys" }