[package]
name = "ruckus"
version = "0.1.0"
authors = ["Andrew Prentice <scalarwaves@null.net>"]
# edition = "2018"

[[bin]]
name = "ruckus"
path = "src/main.rs"

[dependencies]
chuck_sys = { git = "https://github.com/tonal-glyph/chuck-sys" }