[package]
name = "ruckus"
version = "0.1.0"
authors = ["Andrew Prentice <scalarwaves@null.net>"]
edition = "2018"

[lib]
name = "ruckus"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chuck_sys = { path = "../chuck_sys" }
libc = "0.2.48"
midir = "0.5.0"
nom = "4.2.0"
regex = "1.1.0"
rodio = "0.8.1"
rosc = "0.1.5"
rsoundio = "0.1.6"
sdl2 = "0.32.1"
sndfile-sys = "0.1.2"
