[tasks.fetch]
script = [
    "git submodule update --init --recursive && cp -R chuck/src/core lib"
]

[tasks.fmt]
script = [
    "cargo fmt --all && clang-format -i lib/*.c lib/*.h lib/*.cpp lib/lo/*.c lib/lo/*.h lib/regex/*.c lib/regex/*.h"
] 

[tasks.clcm]
script = [
    "rm -rf **/build **/CMakeFiles CMakeFiles CMakeCache.txt **/CMakeCache.txt **/cmake_install.cmake cmake_install.cmake **/compile_commands.json compile_commands.json"
]

[tasks.clnj]
script = [
    "rm -rf **/.ninja* **/*.ninja .ninja* *.ninja"
]

[tasks.gen]
script = [
    "cmake -G Ninja ."
]
dependencies = ["clcm", "clnj"]

[tasks.tags]
script = [
    "ptags chuck"
]

[tasks.flex]
script = [
    "LEX=flex flex -olib/chuck.yy.c lib/chuck.lex"
]

[tasks.flex_win32]
script = [
    "LEX=flex flex --nounistd -olib/chuck.yy.c lib/chuck.lex && cat chuck.tab.c chuck.yy.c > $@"
]

[tasks.yacc]
script = [
    "YACC=bison bison -dv -b lib/chuck lib/chuck.y"
]

[tasks.run]
script = [
    "ninja"
]
dependencies = ["fetch", "fmt", "tags", "yacc", "flex", "gen"]