[tasks.fetch]
script = [
    "git clone https://github.com/ccrma/chuck && cd chuck/src && make linux-pulse && mv chuck chuck-bin && cp chuck-bin ../.."
]

[tasks.fmt]
script = [
    "cargo fmt --all && clang-format -i chuck/src/core/*.c chuck/src/core/*.h chuck/src/core/*.cpp chuck/src/core/lo/*.c chuck/src/core/lo/*.h chuck/src/core/regex/*.c chuck/src/core/regex/*.h"
] 

[tasks.clcm]
script = [
    "rm -rf **/build **/CMakeFiles CMakeFiles CMakeCache.txt **/CMakeCache.txt **/cmake_install.cmake cmake_install.cmake **/compile_commands.json compile_commands.json"
]

[tasks.clnj]
script = [
    "rm -rf **/.ninja* **/*.ninja .ninja* *.ninja"
]

[tasks.cln]
script = [
    "rm -rf chuck/ chuck-bin tags"
]
dependencies = ["clcm", "clnj"]

[tasks.gen]
script = [
    "cmake -G Ninja ."
]
dependencies = ["clcm", "clnj"]

[tasks.tags]
script = [
    "ptags core && ptags host"
]

[tasks.flex]
script = [
    "LEX=flex flex -ochuck/src/core/chuck.yy.c chuck/src/core/chuck.lex"
]

[tasks.flex_win32]
script = [
    "LEX=flex flex --nounistd -ochuck/src/core/chuck.yy.c chuck/src/core/chuck.lex && cat chuck.tab.c chuck.yy.c > $@"
]

[tasks.yacc]
script = [
    "YACC=bison bison -dv -b chuck/src/core/chuck chuck/src/core/chuck.y"
]

[tasks.alsa]
script = [
    "make linux-alsa"
]

[tasks.pulse]
script = [
    "make linux-pulse"
]

[tasks.jack]
script = [
    "make linux-jack"
]

[tasks.make_clean]
script = [
    "make clean"
]

[tasks.run]
script = [
    "ninja && chuck --help"
]
dependencies = ["fetch", "flex", "yacc", "gen", "jack"]
